apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    run: pod
  type: NodePort
status:
  loadBalancer: {}